examples/GMLS_Manifold.cpp
examples/GMLS_Manifold.py.in
src/Compadre_GMLS.cpp
src/Compadre_GMLS.hpp

Added ability for user to set exact tangent bundle (tangent directions plus normal direction) from a rank 3 Kokkos View. The first rank is the target index, next rank is the tangent basis index (or normal for last index), and the thirst rank is the spatial component.
Added tangent approximation test to GMLS_Manifold_Test.

Added setTangentBundle and getTangentBundle member functions for GMLS class

---

CMakeLists.txt
src/Compadre_Evaluator.hpp
src/Compadre_GMLS.cpp
src/Compadre_GMLS.hpp
src/Compadre_GMLS_Quadrature.hpp
src/Compadre_GMLS_Targets.hpp
src/Compadre_LinearAlgebra.cpp
src/Compadre_PointCloudSearch.hpp
src/Compadre_Typedefs.hpp

assert calls are replaced by one of:
compadre_assert_release 
compadre_assert_debug
compadre_kernel_assert_release
compadre_kernel_assert_debug
The difference between **debug** and **release** is that release checks are always performed, so they should not be used inside of compute intense loops. Debug checks are only performed if the CMake variable **Compadre_DEBUG** is set to ON, which it is by default.
compadre_assert... calls are for assertions that are checked on host (CPU) code, while compadre_kernel_assert... calls are for assertions that re checked on the device (GPU) code.
This fixes issue #11

Convert all assert calls to a Compadre specific assert

---

examples/GMLS_Device.cpp
examples/GMLS_Manifold.cpp
examples/GMLS_Staggered_Manifold.cpp
examples/Python_3D_Convergence.py.in
src/Compadre_PointCloudSearch.hpp
src/tpl/nanoflann.hpp

Neighbor search in the Compadre Harness (not the Toolkit, and not publicly available at the moment) is performed in the following way:
1. Perform a radius search (ad-hoc as to how to determine the initial search size), and check whether or not it contains the number of neighbors needed for unisolvency (getNP function from GMLS class). 
2. Get the nth neighbors distance from the target site (call it r_n), where the n is the number of neighbors needed for unisolvency. Multiply this by some amount, generally something around 1.5 (user specified parameter, call it epsilon_multiplier), and set the window size for this target to "epsilon_multiplier * r_n".
3. Perform a new radius neighbor search with the search size of "epsilon_multiplier * r_n" and keep all neighbors that are found.
4. If an …

Changed neighbor searches

---

CMakeLists.txt
doc/Compadre-Install.md
doc/Python-Interface-Install.md
examples/CMakeLists.txt
python/CMakeLists.txt
python/Matlab_1D_Using_Python_Interface.m
python/compadre_py_util.py

Only enabled with Compadre_USE_MATLAB:BOOL=ON, but this option is OFF by default.

Added Matlab example which uses the Python interface to the toolkit

---

src/Compadre_Evaluator.hpp
src/Compadre_GMLS.cpp
src/Compadre_GMLS_Basis.hpp
src/Compadre_LinearAlgebra.cpp
src/Compadre_LinearAlgebra_Definitions.hpp
src/Compadre_Typedefs.hpp

Although the index for the number of problems and each problem's respective dimension can be represented by an int (local_index_type), doing pointer arithmetic in a few locations requires a global_index_type.

Convert pointer arithmetic to global_index_type

---

examples/CMakeLists.txt
examples/GMLS_Vector.cpp
src/Compadre_GMLS.cpp
src/Compadre_GMLS.hpp
src/Compadre_GMLS_Basis.hpp
src/Compadre_GMLS_Targets.hpp
src/Compadre_Operators.hpp

Refactored the GMLS_Targets (not on manifolds) to be organized by
reconstruction space rather than by operation.
Added a setExtraData function allowing a rank 2 matrix to be
available to sampling functionals acting on a basis and on target
operations.
Added SamplingFunctional::FaceNormalIntegralSample and
SamplingFunctional::FaceNormalIntegralSampleData.
Removed the enum EffectiveReconstructionSpaceRank as it was never used.

Added interface for extra data to be made available to basis and target operations in toolkit,

---

src/Compadre_Evaluator.hpp
src/Compadre_GMLS.cpp
src/Compadre_GMLS.hpp
src/Compadre_GMLS_ApplyTargetEvaluations.hpp
src/Compadre_GMLS_Basis.hpp
src/Compadre_GMLS_Quadrature.hpp
src/Compadre_GMLS_Targets.hpp
src/Compadre_LinearAlgebra.cpp
src/Compadre_LinearAlgebra_Declarations.hpp
src/Compadre_LinearAlgebra_Definitions.hpp
src/Compadre_PointCloudSearch.hpp
src/Compadre_Typedefs.hpp

- Create typedefs to execution spaces (host or device)
- Make layout types explicit (layout_left or layout_right, with layout_right being used primarily because it is most efficient for hierarchical parallelism)
- Remove redundant type naming (if it is declared in the header, then use decltype in the cpp file)
- Switch from alphas being rank 2 and P_target_row being rank 1 with a much higher effective rank (by creative indexing) to alphas being rank 3 and P_target_row being rank 2, with the second rank for alphas requiring a function to calculate and the first rank for P_target_row requiring a function to calculate. This exposes maximum parallelism by ensuring the that rank on which dot products are performed are sequential in memory.
- Do a better job with filtering view_type in …

Cleanup and simplify GMLS class

---

examples/GMLS_Device.cpp
examples/GMLS_Manifold.cpp
examples/GMLS_Manifold_Multiple_Evaluation_Sites.cpp
examples/GMLS_Multiple_Evaluation_Sites.cpp
examples/GMLS_SmallBatchReuse_Device.cpp
examples/GMLS_Staggered_Manifold.cpp
examples/GMLS_Vector.cpp
src/Compadre_Evaluator.hpp
src/Compadre_GMLS.cpp
src/Compadre_GMLS.hpp
src/Compadre_GMLS_Basis.hpp
src/Compadre_GMLS_Targets.hpp
src/Compadre_Operators.hpp
src/Compadre_PointCloudSearch.hpp
src/Compadre_Typedefs.hpp

Previously, SamplingFunctionals were an enum having arrays the same size as the enum with characteristics corresponding to each enum member. This more naturally fits the use of a struct, but it was necessary to have this struct be of type constexpr in order to have access to the SamplingFunctional struct instances on both host and device. SamplingFunctionals are now constexpr struct instances, which will make the addition of a new SamplingFunctional by users simpler and less prone to hard-to-find errors.

Changed sampling functionals to constexpr structs

---

examples/GMLS_Host.cpp
python/GMLS_Python.hpp
src/Compadre_Evaluator.hpp
src/Compadre_GMLS.cpp
src/Compadre_Manifold_Functions.hpp

When the reconstruction is made with a gradient of basis, the basis needs to be one higher order for consistency with the expected order of convergence.
The original code update member value `_poly_order` but does not update `_NP`. The latter is used to calculated the dimension of the `P` matrix. This PR fix that bug, along with replacing some runaway tabs in these files.

Fixing a bug for special case in polynomial order

---

src/Compadre_Evaluator.hpp

either
1.) the data sampling functional requested and the one used to construct
the GMLS instance match, OR
2.) the data sampling functional requested is of type 'Identity'

Added assert that when an evaluator is called on a GMLS instance

---

CMakeLists.txt
examples/GMLS_Staggered.cpp
src/Compadre_GMLS.hpp

Now propagate KOKKOS_ENABLE_DEBUG into Kokkos builds, using a default value of whatever Compadre_DEBUG is set to, which by default is ON. This allows Kokkos to be built in a mode independent of Compadre.
Fixed a size variable that didn't take into account that when a gradient is needed for curvature and only a scalar target is selected, the size would have been incorrect.
Replaced two NULL statements in a test that require an integer.

KOKKOS_ENABLE_DEBUG CMake flag now propagated

---

examples/CMakeLists.txt
examples/GMLS_Device.cpp
examples/Python_3D_Convergence.py.in
python/GMLS_Module.py.in
python/GMLS_Module_wrap.cxx
python/GMLS_Python.hpp
src/CMakeLists.txt
src/Compadre_KokkosParser.cpp
src/Compadre_KokkosParser.hpp

Added a KokkosParser class that acts as a scope-guard for Kokkos initialization.
This takes the place of calling Kokkos::initialize() and Kokkos::finalize(), with the instantiation of KokkosParser objects calling initializing, and calling finalizing automatically upon object destruction.
Added access to this object with a Kokkos_Python object for the Python interface.
It is now possible to initialize Kokkos through the Python interface, calling for a particular GPU device.

KokkosParser class added

---

examples/GMLS_DivergenceFree.cpp
examples/GMLS_Tutorial.hpp
src/Compadre_GMLS_Targets.hpp
src/Compadre_Operators.hpp

Add curl and curl operators acting on div-free vector fields. Changes include:
1. Define new `enum` for operator inside `Compadre_Operators.hpp`
2. Add the evaluation of basis on curl and curl-curl operators inside `Compadre_GMLS_Targets.hpp`.
3. Add unit tests for these operators inside `examples/GMLS_DivergenceFree.cpp`.

Add curl and curl-curl operator acting on div-free vector fields

---

CMakeLists.txt
src/Compadre_GMLS_ApplyTargetEvaluations.hpp
src/Compadre_GMLS_Basis.hpp
src/Compadre_Typedefs.hpp

Enabled by CMake variable Compadre_EXTREME_DEBUG:BOOL=ON
By default, this is OFF.
Added compadre_kernel_assert_extreme_debug and compadre_assert_extreme_debug.
Checks on P matrix and on alpha generation were moved from regular debug to
extreme debug (very slow, but thorough).

Added extreme debug mode

---

examples/CMakeLists.txt
examples/GMLS_Device.cpp
python/GMLS_Module.i
python/GMLS_Module_wrap.cxx
python/run_swig.sh
src/Compadre_GMLS.cpp
src/Compadre_GMLS.hpp
src/Compadre_GMLS_ApplyTargetEvaluations.hpp
src/Compadre_GMLS_Basis.hpp
src/Compadre_GMLS_Targets.hpp
src/Compadre_KokkosParser.hpp
src/Compadre_LinearAlgebra.cpp
src/Compadre_LinearAlgebra_Declarations.hpp
src/Compadre_Typedefs.hpp

generateAlphas() and generatePolynomialCoefficients() now take an optional argument (const int number_of_batches), that allows the user to split the total load into smaller batches that can be executed in parallel. 
Originally, the toolkit relied on Kokkos::parallel_for to create batches/batch sizes, but because of the need to enter and exit device code multiple times, it was necessary to allocate enough space for all matrices needed for the computation and have them persist between calls.
For modest sized computations, this provided the best of both worlds, a persistent set of matrices as well as the ability to call code from the host (Cuda and LAPACK calls). However, when performing computations for a large number of targets, it is possible that all of these matrices can not be stored …

Support many batches rather than only all-at-once

---

src/Compadre_GMLS.cpp

Replace the two for loops (for transposing the matrix and copying the 1D data over) inside the LU solver with `Kokkos::parallel_for`.

Replacer for loop with Kokkos::parallel_for

---

src/CMakeLists.txt
src/Compadre_Functors.hpp
src/Compadre_GMLS.cpp
src/Compadre_GMLS.hpp
src/Compadre_ParallelManager.hpp

There were many member variables and private member functions for calling Kokkos functors inside of the GMLS class. Much of this could be abstracted and called from in a way that allows it to be reused for launching other functors that are not in the GMLS class.

Extracted parallel kernel sizing and calling from GMLS class into ParallelManager

---

src/Compadre_GMLS.cpp
src/Compadre_Misc.hpp

Add a function to calculate the dimension for the square `RHS` matrix. This will allow the RHS to be much smaller in solving with LU. The interface to change the matrix dimension can also be useful when adding extra constraints to the minimisation least-square problem.

Allow RHS to be adjustable 

---

src/Compadre_GMLS.cpp
src/Compadre_Misc.hpp

Use a function to return the size of matrix `_P` based on the solver type and the constraint type. This is necessary to move toward solving the saddle-point problem in Neumann BC.

Changing size of matrix P based on solver type and constraints

---

physics/Compadre_GMLS_PoissonNeumann_Operator.cpp
physics/Compadre_GMLS_PoissonNeumann_Operator.hpp

Replacing `generateData` with `initialize` that was made available.

Quick fix to use initialize function instead

---

examples/CMakeLists.txt
examples/GMLS_Staggered.cpp
examples/UnitTest_ThreadedLapack.cpp
src/Compadre_GMLS.cpp
src/Compadre_GMLS.hpp
src/Compadre_GMLS_ApplyTargetEvaluations.hpp
src/Compadre_LinearAlgebra.cpp
src/Compadre_LinearAlgebra_Declarations.hpp
src/Compadre_Misc.hpp
src/basis/CreateConstraints.hpp

Basically Re PR #148 but without the unnecessary file. 
Since this PR spans two separate decades, a lot of things are bounded to happen.
* When solving the Neumann constraint with GMLS, the staggered scheme introduce a row of 0 in th P^TWP matrix. This PR allows SVD to solve the square system P^T W P against P^T W
* The original code of SVD post-multiply the factorization with a diagonal matrix (solving P^T sqrt(W) against sqrt(W) ) hence allowing a trick to be used. This PR check the switch and perform full matrix multiplication if necessary.
* Consider solving the constraint Neumann with Vector reconstruction space. When the target operator is `DivergenceOfVector`, the added rows and columns to the M = P^T W P matrix is equal to the dimension of the space, but the additional alpha is …

Allowing SVD to solve GMLS problem with Staggered Scheme and Neumann BC

---

CMakeLists.txt
cmake/bob.cmake
python/setup.py.in
src/CMakeLists.txt

Looked for optional OpenMP and link target if found.
Bump CMake version to 3.10.0 requires (Same as Kokkos and Trilinos)
Changed to
>> pip install compadre --install-option="--cmake-file=/some/absolute/path/to/file/with/cmake/variables.txt"
Removed all cmake module importing in setup.py created by toolkit.
Now, if cmake can be called (such as from sudo apt-get install cmake),
that will also work, and it won't necessarily require the cmake python
module which can be problematic to install.

Version 1.0.3

---

src/Compadre_ProblemT.cpp
src/Compadre_ProblemT.hpp
src/Compadre_SolverT.cpp
src/Compadre_SolverT.hpp

to get the residual stored on particles.
This assists with visual debugging.
Exact solution can be put on particles in between solver() and residual() call
which will test the forward action of the operator on the exact solution.
Address issue #178

Added residual() function that can be called after solve() on ProblemT

---

scripts/snapshot_into_trilinos.py

Create script to snapshot the Compadre repository containing the script into the Trilinos pointed to on the command line, excluding the `kokkos`, `kokkos-kernels`, `python`, and `scripts` directories, utilizing the `SnapshotDir` utility from TriBITS under the hood.
Closes #175.

Resolve "Create Script to Snapshot Compadre into Trilinos"

---

scripts/snapshot_into_trilinos.py

Before #173 was merged, the files excluded by the snapshotting script were adjusted, but the corresponding unit test wasn't.  This adjusts the unit test such that pytest is passing again.  Running `pytest snapshot_into_trilinos.py` now yields
```
================================================ test session starts ================================================
platform linux -- Python 3.7.7, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /workspace/compadre/scripts
plugins: arraydiff-0.3, astropy-header-0.1.1, doctestplus-0.5.0, openfiles-0.4.0, remotedata-0.3.2
collected 4 items                                                                                                   
snapshot_into_trilinos.py .... …
```

Fix Snapshot Unit Test

---

examples/GMLS_Device.cpp
examples/GMLS_SmallBatchReuse_Device.cpp
examples/GMLS_Vector.cpp
src/Compadre_GMLS.cpp
src/Compadre_GMLS.hpp

Added keep_coefficients argument to generateAlphas() and generatePolynomialCoefficients() which is set to false by default. If false, then solution to (PTWP^-1 * PTW deallocated after its use in generating the alpha coefficients.
Descriptive error is given when trying to access coefficients that arechosen not to be stored. Check added that if storing coefficients, number of batches must be equal to 1 (otherwise all coefficients weren't stored, anyways).
Tests that access polynomial coefficients have been modified to use the true flag for keep_coefficients when calling generateAlphas().

Added keep_coefficients argument to generateAlphas()

---

CMakeLists.txt
src/CMakeLists.tribits.cmake
src/CMakeLists.txt
src/Compadre_GMLS.cpp
src/Compadre_GMLS.hpp
src/Compadre_PointCloudSearch.hpp

Toolkit now includes GNUInstallDirs to populate CMAKE_INSTALL_LIBDIR.
If being built as child outside of Trilinos (like in the harness), it
will rely on the outer package defining CMAKE_INSTALL_LIBDIR.
Added build interface target_include_directories for compadre target,
which allow for flat header including, e.g.
\#include "some_basis.hpp"
will now work, even if some_basis.hpp is in "basis/some_basis.hpp"
Because all header files are installed into a flat /include structure,
this is important so that users can build against an installed Compadre
toolkit and use it's headers.

Fixed populating CMAKE_INSTALL_LIBDIR and including header for subdirectories.

---

examples/Compadre_ReactionDiffusion.cpp
physics/Compadre_ReactionDiffusion_Operator.cpp
physics/Compadre_ReactionDiffusion_Sources.cpp
src/Compadre_PhysicsT.hpp
test_data/parameter_lists/reactiondiffusion/parameters_template.xml
test_data/utilities/variational_convergence.py

This SHA used to generate results for REBAR SAND report for reaction-diffusion and Stokes flow.
Linear elasticity was done in May of 2020.
Corrected Cell->Particle and Particle->Cell neighborhoods ordering.
Previously, they were backwards but it didn't matter at that point
becauses Cells==Particles previously.

Enabled particle sets separate from cell midpoints for REBAR

---

physics/Compadre_GMLS_Stokes_Operator.cpp
physics/Compadre_LagrangianShallowWater_BoundaryConditions.cpp
physics/Compadre_LagrangianShallowWater_Operator.cpp
physics/Compadre_LagrangianShallowWater_Sources.cpp
physics/Compadre_LaplaceBeltrami_Operator.cpp
src/CompadreHarness_Typedefs.hpp
src/Compadre_BoundaryConditionsT.hpp
src/Compadre_FieldManager.cpp
src/Compadre_FieldManager.hpp
src/Compadre_FieldSparsity.hpp
src/Compadre_FieldT.hpp
src/Compadre_PhysicsT.hpp
src/Compadre_ProblemExplicitTransientT.cpp
src/Compadre_ProblemExplicitTransientT.hpp
src/Compadre_ProblemT.hpp
src/Compadre_SourcesT.hpp
test_data/parameter_lists/shallow_water/parameters_case2.xml

Compadre_FieldManager.hpp. Similar for enum for operation type.
FieldSparsity enum moved to Compadre_FieldSparsity.hpp
ProblemExplicitTransientT updated so that operations needing
performed for field interactions are sorted resulting in Dirichlet
boundary conditions being performed first, RHS being assembled 2nd,
and the action of the operator last.

Moved InteractingFields out of CompadreHarness_Typedefs.h, fixed field registration

---

examples/Compadre_UnitTests.cpp
examples/Python_3D_Convergence.py.in
examples/unittests/test_LinearAlgebra.hpp
pycompadre/pycompadre.cpp
src/Compadre_KokkosParser.cpp
src/Compadre_KokkosParser.hpp
src/Compadre_Misc.hpp

Removed all of the manual setting of numa, threads, ngpus, etc...
from the KokkosParser class. Added convenient constructors to the
KokkosParser class that allow for command line argc and argv to be
given or a std::vector<std::string> or an empty constructor.
KokkosParser::status(...) now will get Kokkos::print_configuration.
This ensures that all Kokkos configuration settings are set via command line like arguments.

Simplify the KokkosParser functionality

---

examples/test_pycompadre.py
pycompadre/pycompadre.cpp
src/Compadre_NeighborLists.hpp

Exposed getAlpha from the GMLS class, which allows for access to
the individual alpha values generated by GMLS.
setAdditionalEvaluationSitesData allows for the evaluation at
locations other than just target sites.

Add getAlpha and setAdditionalEvaluationSitesData to pycompadre

---

pycompadre/pycompadre.cpp
src/Compadre_GMLS.hpp

- Neighbor lists use the NeighborLists class in the GMLS class and additional_evaluation_indices were still using the rank 2 vector style storage of additional evaluation site indices.
- Now GMLS class supports both styles of neighbor lists for the additional evaluation indices.
- Add applyStencilAllTargetsAllAdditionalEvaluationSites for pycompadre.

Made additional evaluation data consistent with neighbor lists in GMLS class

---

src/Compadre_PointConnections.hpp

- Previously, both functions assumed 2D manifold in 3D ambient space.
Modified to support m dimension manifold in n ambient space dimensions
with 1<=m<n.

Fix getNeighorCoordinate and getTargetCoordinate for manifold

---

src/Compadre_LinearAlgebra.cpp
src/tpl/KokkosBatched_SolveUTV_TeamVector_Internal_Compadre.hpp

- Uses Kokkos::printf() for Kokkos>=4.2
- Contributed from https://github.com/trilinos/Trilinos/pull/12502

Fix printf for SYCL

---

src/Compadre_Operators.hpp
src/Compadre_Quadrature.hpp

- Declare enum type explicitly

Fix enum for SYCL
