sandialabs/compadre

CMakeLists.txt, src/CMakeLists.txt, src/Compadre_OBFET.cpp
Even if turned on, it is built for user automatically. Resolves #38
=> Made 'compose' library optional with CMake variable Compadre_USE_Compose

examples/GMLS_Manifold.cpp, src/Compadre_GMLS.cpp, src/Compadre_GMLS.hpp
=> Add setting and getting of reference outward normal direction as well as surface reorientation for manifolds.

src/Compadre_GMLS.cpp, src/Compadre_GMLS.hpp
=> Changed maximum neighbor count

examples/GMLS_Device.cpp, examples/GMLS_Host.cpp, examples/GMLS_Manifold.cpp, examples/GMLS_Manifold_Multiple_Evaluation_Sites.cpp, examples/GMLS_Multiple_Evaluation_Sites.cpp, examples/GMLS_SmallBatchReuse_Device.cpp, examples/GMLS_Staggered_Manifold.cpp, examples/GMLS_Vector.cpp, examples/UnitTest_ThreadedLapack.cpp, src/Compadre_Evaluator.hpp, src/Compadre_GMLS.cpp, src/Compadre_GMLS.hpp, src/Compadre_PointCloudSearch.hpp
=> Kokkos deprecated fix

CMakeLists.txt, doc/Doxyfile.in
Allows for easier deployment to gh-pages
=> Changed doxygen to build in-source rather than in the build directory.

src/Compadre_GMLS.cpp
=> Added assert for prestencil weight that was only meant to be used on manifolds.

src/Compadre_PointCloudSearch.hpp
It is a recoverable error when preallocated space is insufficient, but it was previously resulting in an abort if not satisfied. Now, by reduction over number of neighbors found, we can throw an exception when preallocated space is insufficient that can be recovered from.
=> Changed PointCloudSearch to remove kernel asserts 

examples/GMLS_Device.cpp, examples/GMLS_DivergenceFree.cpp, examples/GMLS_Host.cpp, examples/GMLS_Manifold.cpp, examples/GMLS_Manifold_Multiple_Evaluation_Sites.cpp, examples/GMLS_Multiple_Evaluation_Sites.cpp, examples/GMLS_SmallBatchReuse_Device.cpp, examples/GMLS_Staggered.cpp, examples/GMLS_Staggered_Manifold.cpp, examples/GMLS_Vector.cpp, python/GMLS_Python.hpp, src/Compadre_GMLS.hpp, src/Compadre_Operators.hpp
* Change the `BoundaryType` into `ConstraintType` 
* Change `DIRICHLET` into `NO_CONSTRAINT` (cannot change to `NONE` due to conflict with Optimization choice from `harness`)
* Change `NEUMANN` into `NEUMANN_GRAD_SCALAR`
* Adapt the new changes to examples inside `TOOLKIT`
* Address issue #105
=> Toolkit - change boundary type to constraint type

src/Compadre_Evaluator.hpp, src/Compadre_GMLS.cpp, src/Compadre_GMLS_ApplyTargetEvaluations.hpp, src/Compadre_LinearAlgebra.cpp
Changed indices ordering to be consistent with this change.
=> Convert solutions from LAPACK/CUDA to layout right

src/Compadre_GMLS.hpp, src/Compadre_GMLS_Basis.hpp
Added additional neighbor index to getAlpha() functions.
=> Moved Wab and EuclideanVectorLength to static functions

src/Compadre_GMLS.cpp
Adjusting linear algebra solver for manifold problems to allow LU to be used throughout.
=> Adapting LU factorization to be used through the whole manifold solver

examples/CMakeLists.txt, examples/GMLS_NeumannGradScalar.cpp, src/CMakeLists.txt, src/Compadre_GMLS.cpp, src/Compadre_GMLS.hpp, src/Compadre_GMLS_ApplyTargetEvaluations.hpp, src/Compadre_Misc.hpp, src/basis/CreateConstraints.hpp
* Restructure M/PsqrtW matrix to allow extra sizes for the constraints.
* Add a function in Compadre_Misc.hpp to calculate the extra size for the constraint
* Solve the new constraint solution and provide a test case inside examples/GMLS_NeumannGradScalar.cpp
=> Add capability to solve GMLS with Neumann Gradient Scalar constraint

toolkit/examples/GMLS_NeumannGradScalar.cpp, toolkit/src/basis/CreateConstraints.hpp
Fix a missing file in `src/basis` from Toolkit SHA 908844b
=> Fix missing files from Toolkit SHA 908844b

examples/CMakeLists.txt, examples/UtilityTest.cpp, src/Compadre_Utilities.hpp
Add the filter function - to capture the indices of certain flags - and extract - to create a smaller view of the large 2D view where the rows are corresponding to the captured flags.
Add the unit test to perform testing for this capability.
=> Add functionality to filter and extract the 2D array based on the flag value

examples/GMLS_Staggered.cpp, src/Compadre_GMLS_Targets.hpp
This PR adds a simple demonstration on how to evaluate the gradient using the `VectorPolynomialBasis` with `StaggeredEdgeIntegralSample`.
=> Add capability of evaluating the gradient inside staggered (non-manifold) test

examples/CMakeLists.txt, examples/GMLS_Device.cpp, examples/GMLS_DivergenceFree.cpp, examples/GMLS_Manifold.cpp, examples/GMLS_Manifold_Multiple_Evaluation_Sites.cpp, examples/GMLS_Multiple_Evaluation_Sites.cpp, examples/GMLS_NeumannGradScalar.cpp, examples/GMLS_SmallBatchReuse_Device.cpp, examples/GMLS_Staggered.cpp, examples/GMLS_Staggered_Manifold.cpp, examples/GMLS_Tutorial.hpp, examples/GMLS_Vector.cpp, examples/UnitTest_ThreadedLapack.cpp, python/GMLS_Python.hpp, src/Compadre_Evaluator.hpp, src/Compadre_GMLS.cpp, src/Compadre_GMLS.hpp, src/Compadre_GMLS_ApplyTargetEvaluations.hpp, src/Compadre_GMLS_Targets.hpp, src/Compadre_LinearAlgebra.cpp, src/Compadre_LinearAlgebra_Declarations.hpp, src/Compadre_Misc.hpp, src/Compadre_Operators.hpp, src/Compadre_PointCloudSearch.hpp, src/Compadre_Quadrature.hpp, src/Compadre_Utilities.hpp, src/basis/CreateConstraints.hpp
I have enabled the target operation of gradient of divergence free basis. The unit test is only set for 3D case of gradient check. The naming in the evaluator may need some modification to keep it consistent.
=> enable gradient of divergence free basis and evaluation over rank 2 output target

examples/CMakeLists.txt, examples/Canga_Test_Intercomparison.cpp, examples/Compadre_ReactionDiffusion.cpp, physics/Compadre_ReactionDiffusion_BoundaryConditions.cpp, physics/Compadre_ReactionDiffusion_BoundaryConditions.hpp, physics/Compadre_ReactionDiffusion_Operator.cpp, physics/Compadre_ReactionDiffusion_Operator.hpp, physics/Compadre_ReactionDiffusion_Sources.cpp, src/Compadre_AnalyticFunctions.cpp, src/Compadre_AnalyticFunctions.hpp, test_data/parameter_lists/reactiondiffusion/parameters_template.xml, test_data/utilities/variational_convergence.py
Also implements working variational Stokes flow solver.
=> Refactored AnalyticFunction and most derived classes

scripts/snapshot_into_trilinos.py, src/Compadre_GMLS.cpp, src/Compadre_GMLS.hpp, src/Compadre_NeighborLists.hpp, src/Compadre_PointCloudSearch.hpp
This is an addition to the fix for #205
=> Converted row_offsets in NeighborLists class over to global_index_type

examples/CMakeLists.txt, examples/Compadre_GMLSStaggeredPoissonNeumannTest.cpp, examples/Compadre_GMLSStokesTest.cpp, physics/CMakeLists.txt, physics/Compadre_GMLS_Staggered_PoissonNeumann_Operator.cpp, physics/Compadre_GMLS_Staggered_PoissonNeumann_Operator.hpp, physics/Compadre_GMLS_Staggered_PoissonNeumann_Sources.cpp, physics/Compadre_GMLS_Staggered_PoissonNeumann_Sources.hpp, physics/Compadre_GMLS_Stokes_BoundaryConditions.cpp, physics/Compadre_GMLS_Stokes_BoundaryConditions.hpp, physics/Compadre_GMLS_Stokes_Operator.cpp, physics/Compadre_GMLS_Stokes_Operator.hpp, physics/Compadre_GMLS_Stokes_Sources.cpp, physics/Compadre_GMLS_Stokes_Sources.hpp, src/Compadre_AnalyticFunctions.cpp, src/Compadre_AnalyticFunctions.hpp, test_data/grids/make_cube_mixed_dirichlet_neumann.py, test_data/grids/make_cube_with_normals.py, test_data/parameter_lists/gmls_stokes/parameters_amg.yml, test_data/parameter_lists/gmls_stokes/solver_amg.xml
* Creating new test `StaggeredPoissonNeumann`, which solve the Poisson problem with mixed Neumann-Dirichlet problem with staggerd scheme. Adding corresponding physics files.
* Creating new test `Stokes` test problem, which solve the Stoke's problem on a cube mesh. Adding corresponding physics file.
* Rename previous mesh files `cube_normals_*` into `cube_with_normals_*` which only have internal points (flagged 0) and external points (flagged 1). Also create `cube_mixed_dirichlet_neumann_*`, which includes Dirichlet BC points (flagged 1) and Neumann BC points (flagged 2) along with internal points (flagged 0).
* Add new functions inside `src/Analytic_Functions` to allow for Stoke's solutions.
Mesh files are to be added later.
=> Adding Stoke's test problem into Harness

src/Compadre_GMLS.cpp, src/Compadre_GMLS_ApplyTargetEvaluations.hpp
In case the problem size overshoots int type
=> Fix type for base_target_index

kokkos-kernels/src/batched/KokkosBatched_Gemm_Serial_Internal.hpp, kokkos-kernels/src/batched/KokkosBatched_Gemm_TeamVector_Impl.hpp, kokkos-kernels/src/batched/KokkosBatched_Gemm_Team_Internal.hpp, src/Compadre_GMLS.cpp
Previously we were using the internal interface, which is not advisable.
=> Switch to using public interface for KK Batched Gemm

examples/Compadre_ReactionDiffusion.cpp, physics/Compadre_ReactionDiffusion_Operator.cpp, physics/Compadre_ReactionDiffusion_Sources.cpp
1. Refactoring of computation of vms stabilization parameter (tau)
2. Updated VMS edge bubble definition
3. Heuristic correction to tau for overlapping sectors (edge bubble support)
4.  Used stabilization parameter (tau) for jump norm of error when using vms
=> Manual VMS update merge:

CMakeLists.txt, examples/unittests/test_NeighborLists.hpp, src/Compadre_Basis.hpp, src/Compadre_NeighborLists.hpp, src/Compadre_Targets.hpp
- Forces Compadre_DEBUG to be ON when Compadre_EXTREME_DEBUG is ON
- Adds some extreme debug assertions for neighbor lists accessor
=> Modify Compadre_DEBUG logic when Compadre_EXTREME_DEBUG is ON
